website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .helpers import get_barber_by_id, allowed_file, save_picture
from .models import Barber_detail
from werkzeug.utils import secure_filename
from . import db
import os

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html", user=current_user)

@views.route('/test')
def hometest():
    return render_template("hometest.html", user=current_user)

@views.route('/profile/<int:barber_id>')
def profile(barber_id):
    barber = get_barber_by_id(barber_id)

    # Check if the barber's picture is set. if not, render a default.
    if not barber.barber_detail.picture_filename:
        barber.barber_detail.picture_filename = 'default.jpg'

    return render_template("profile.html", barber=barber, user=current_user)


@views.route('/barbers')
def barbers():
    barbers = Barber_detail.query.all()
    return render_template("barber_list.html", user=current_user, barbers=barbers)

@views.route('/reviews')
def reviews():
    barbers = Barber_detail.query.all()
    return render_template("reviews.html", user=current_user, barbers=barbers)

website/templates/add_service.html
{% extends "base.html" %}
{% block title %}New Service{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-5">
                <h3 class="text-center mb-4">Add Service</h3>

                <!-- Barber Service -->
                <div class="form-group mb-3">
                    <label for="service">Barber Service</label>
                    <input type="text" class="form-control" id="service" name="service" placeholder="Service Name" aria-label="Barber Service">
                </div>

                <!-- Description of the Service -->
                <div class="form-group mb-3">
                    <label for="description">Description of the Service (max 150 characters)</label>
                    <input type="text" maxlength="150" class="form-control" id="description" name="description" placeholder="Describe the Service" aria-label="Description of the Service">
                </div>

                <!-- Price of the Service -->
                <div class="form-group mb-3">
                    <label for="price">Price of the Service ($)</label>
                    <input type="number" class="form-control" id="price" name="price" placeholder="Enter price" aria-label="Price of the Service">
                </div>

                <!-- Duration of the Service -->
                <div class="form-group mb-4">
                    <label for="duration">Duration</label>
                    <select name="duration" id="duration" class="form-control" aria-label="Duration of the Service">
                        <option value="15">15 minutes</option>
                        <option value="30">30 minutes</option>
                        <option value="45">45 minutes</option>
                        <option value="60">1 hour</option>
                        <option value="75">1 hour 15 minutes</option>
                        <option value="90">1 hour 30 minutes</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary w-100">Create Service</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/barber_dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="container-xl px-4 mt-4">
    <nav class="nav nav-borders">
        <a class="nav-link active ms-0" href="{{ url_for('dashboard.edit_profile') }}">Edit Profile</a>
        <a class="nav-link" href="{{ url_for('dashboard.edit_availability') }}">Availability</a>
        <a class="nav-link" href="{{ url_for('dashboard.barber_services') }}">Edit Services</a>
        <a class="nav-link" href="{{ url_for('messages.home') }}">Inbox</a>
    </nav>
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4 text-center">
                            <img src="{{ url_for('static', filename='photos/profile_pictures/' + (user.barber_detail.picture_filename if user.barber_detail.picture_filename else 'default.jpg')) }}" alt="{{ user.name }}" class="img-fluid profile-picture rounded-circle w-75">
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">User Information</h5>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Name: <strong>{{ user.name }}</strong></li>
                                <li class="list-group-item">E-Mail: <strong>{{ user.email }}</strong></li>
                                <li class="list-group-item">Phone Number: <strong>{{ user.phone_number }}</strong></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="container">
            <h3 class="mt-4 mb-4">Appointments</h3>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Date (YYYY-MM-DD)</th>
                            <th>Time</th>
                            <th>Client</th>
                            <th>Service</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for appointment in appointments %}
                            <tr>
                                <td>{{ appointment.datetime.strftime('%Y-%m-%d') }}</td>
                                <td>{{ appointment.datetime.strftime('%I:%M %p') }}</td>
                                <td>{{ appointment.client.name }}</td> 
                                <td>{{ appointment.service.name }}</td>
                                <td>{{ appointment.client.email }}</td>
                                <td>{{ appointment.client.phone_number}}</td>
                                <td>
                                    <form method="POST" action="{{ url_for('book.delete_appointment', appointment_id=appointment.appointment_id) }}" class="d-inline">
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                    <a href="{{ url_for('messages.send_message', reply_to=appointment.client.user_id) }}" class="d-inline btn btn-primary btn-sm">Message</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/barber_list.html
{% extends 'base.html' %}
{% block title %}The Team{% endblock %}
{% block content %}
<style>
    .custom-card {
        background-color: #1e1e1e;
        border: 1px solid #333;
    }

    .text-grey {
        color: #cacaca;
    }

    .rounded-circle {
        width: 150px;
        height: 150px;
    }

    @media (max-width: 768px) {
        .rounded-circle {
            width: 100px;
            height: 100px;
        }

        .col-md-4 {
            flex-basis: 50%;
        }
    }

    .btn {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
        transform-origin: center;
    }

    .btn:hover {
        transform: scale(1.1);
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
    }
</style>

<div class="container mt-5">
    <h1 class="text-left">The Team</h1>
    <div class="row">
        {% for barber in barbers %}
        <div class="col-md-4 mb-4">
            <div class="card custom-card">
                <img src="{{ url_for('static', filename='photos/profile_pictures/' + (barber.picture_filename if barber.picture_filename else 'default.jpg')) }}" class="card-img-top rounded-circle responsive-img mt-3 ms-3" alt="{{ barber.name }}">
                <div class="card-body">
                    <h5 class="card-title text-grey">{{ barber.user.name }}</h5>
                    <a href="https://www.instagram.com/{{ barber.instagram_tag }}" target="_blank" class="btn btn-primary btn-sm">
                        <i class="fab fa-instagram"></i> Instagram
                    </a>
                    <a href="{{ url_for('views.profile', barber_id=barber.barber_id) }}" class="btn btn-secondary btn-sm">View Profile</a>
                    <a href="{{ url_for('book.book_appointment', barber_id=barber.barber_id) }}" class="btn btn-success btn-sm">Book Now</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, inital-scale=1">
        
        <!-- Bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&family=Source+Sans+3:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
        
        <title> {% block title %}Home{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg">
            <div class="navbar-brand-container">
                <div class="navbar-brand">
                    HEADLINERS BARBERSHOP
                </div>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav ms-3">
                    <!-- Always shown links -->
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="barbers" href="/barbers">The Team</a>
                </div>
                <div class="navbar-nav ms-auto me-3">
                    {% if user.is_authenticated %}
                    <!-- Links for authenticated users -->
                        {% if user.role == 'barber' %}
                            <!-- Links for barbers only -->
                            <a class="nav-item nav-link" id="profile" href="{{ url_for('views.profile', barber_id=current_user.barber_detail.barber_id) }}">Profile</a>
                        {% endif %}
                        <a class="nav-item nav-link" id="dashboard" href="{{ url_for('dashboard.home' )}}">Dashboard</a>
                        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" id="login" href="/login">Login</a>
                        <a class="nav-item nav-link" id="sign-up" href="/sign-up">Sign Up</a>             
                    {% endif %}
                </div>
            </div>
        </nav>

            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'danger' %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                    {% else %}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>     
                    {% endif %}        
                {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    </body>

</html>

website/templates/book_appointment.html
{% extends "base.html" %}
{% block title %}Book Appointment{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-5">
                <h3 class="text-center mb-4">Book an Appointment</h3>

                <!-- Service Dropdown -->
                <div class="form-group mb-3">
                    <label for="service">Select Service</label>
                    <select class="form-select" id="service" name="service" aria-label="Select Service">
                        {% for service in services %}
                            <option value="{{ service.barber_service_id }}">{{ service.name }} (${{ service.price }})</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Date Picker -->
                <div class="form-group mb-3">
                    <label for="date">Select Date</label>
                    <input type="date" class="form-control" id="date" name="date" value="{{ selected_date.strftime('%Y-%m-%d') }}" aria-label="Select Date">
                </div>

                <!-- Time Slot Dropdown -->
                <div class="form-group mb-4">
                    <label for="timeSlot">Select Time Slot</label>
                    <select class="form-select" id="timeSlot" name="timeSlot" aria-label="Select Time Slot">
                        {% for slot in available_time_slots %}
                            <option value="{{ slot }}">{{ slot }}</option>
                        {% endfor %}
                    </select>
                </div>

                <button type="submit" class="btn btn-primary w-100">Book Appointment</button>
            </form>
        </div>
    </div>
</div>

<!-- script to update the URL when the date changes -->
<script>
    document.getElementById('date').addEventListener('change', function() {
        var selectedDate = this.value;
        window.location.href = "{{ url_for('book.book_appointment', barber_id=barber.barber_id) }}?date=" + selectedDate;
        console.log("Selected Date:", selectedDate);
    });
</script>
{% endblock %}

website/templates/conversation_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center">
        <h2>Conversation with {{ partner.name }}</h2>
        <div class="ms-auto">
            <a href="{{ url_for('messages.home') }}" class="btn btn-secondary">Back</a>
            <a href="{{ url_for('messages.send_message', reply_to=partner.user_id) }}" class="btn btn-primary">Reply</a>
        </div>
    </div>
    <div class="list-group mt-3">
        {% for message in messages %}
            <div class="list-group-item">
                <strong>{{ message.sender.name }}:</strong>
                <p>{{ message.content }}</p>
                <small>{{ message.timestamp.strftime('%I:%M%p %m/%d/%Y') }}</small>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/edit-services.html
{% extends "base.html" %}
{% block title %}Service Editor{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-5">
                <h3 class="text-center mb-4">Create Barber Service</h3>

                <!-- Barber Service -->
                <div class="form-group mb-3">
                    <label for="service">Barber Service</label>
                    <input type="text" class="form-control" id="service" name="service" {{ name_string }} aria-label="Barber Service">
                </div>

                <!-- Description of the Service -->
                <div class="form-group mb-3">
                    <label for="description">Description of the Service</label>
                    <input type="text" maxlength="150" class="form-control" id="description" name="description" placeholder="Describe the service (max 150 chars)" aria-label="Description of the Service">
                </div>

                <!-- Price of the Service -->
                <div class="form-group mb-3">
                    <label for="price">Price of the Service ($)</label>
                    <input type="number" class="form-control" id="price" name="price" placeholder="Enter price" aria-label="Price of the Service">
                </div>

                <!-- Duration of the Service -->
                <div class="form-group mb-4">
                    <label for="duration">Duration</label>
                    <select name="duration" id="duration" class="form-control" aria-label="Duration of the Service">
                        <option value="15">15 minutes</option>
                        <option value="30">30 minutes</option>
                        <option value="45">45 minutes</option>
                        <option value="60">1 hour</option>
                        <option value="75">1 hour 15 minutes</option>
                        <option value="90">1 hour 30 minutes</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary w-100">Create Service</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/edit_service.html
{% extends "base.html" %}
{% block title %}Service Editor{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-5">
                <h3 class="text-center mb-4">Edit Barber Service</h3>

                <!-- Barber Service -->
                <div class="form-group mb-3">
                    <label for="service">Barber Service</label>
                    <input type="text" class="form-control" id="service" name="service" value="{{ service.name }}" aria-label="Barber Service">
                </div>

                <!-- Description of the Service -->
                <div class="form-group mb-3">
                    <label for="description">Description of the Service (max 150 characters)</label>
                    <input type="text" maxlength="150" class="form-control" id="description" name="description" value="{{ service.desc }}" aria-label="Description of the Service">
                </div>

                <!-- Price of the Service -->
                <div class="form-group mb-3">
                    <label for="price">Price of the Service ($)</label>
                    <input type="number" class="form-control" id="price" name="price" value="{{ service.price }}" aria-label="Price of the Service">
                </div>

                <!-- Duration of the Service -->
                <div class="form-group mb-4">
                    <label for="duration">Duration</label>
                    <select name="duration" id="duration" class="form-control" aria-label="Duration of the Service">
                        <option value="15" {% if service.duration == 15 %}selected{% endif %}>15 minutes</option>
                        <option value="30" {% if service.duration == 30 %}selected{% endif %}>30 minutes</option>
                        <option value="45" {% if service.duration == 45 %}selected{% endif %}>45 minutes</option>
                        <option value="60" {% if service.duration == 60 %}selected{% endif %}>1 hour</option>
                        <option value="75" {% if service.duration == 75 %}selected{% endif %}>1 hour 15 minutes</option>
                        <option value="90" {% if service.duration == 90 %}selected{% endif %}>1 hour 30 minutes</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary w-100">Update Service</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Headliners Home{% endblock %}

{% block content %}

<style>

    .video-background {
        position: fixed;
        top: 0;
        left: 0;
        width: 100vw;
        height: 100vh;
        overflow: hidden;
        z-index: -1; 
    }

    .video-foreground,
    .video-background iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        pointer-events: none;
    }

    .content-container {
        position: relative;
        z-index: 1;
    }

    .logo-container {
        position: absolute;
        top: 50%; 
        left: 50%; 
        transform: translate(-50%, 150%); 
        z-index: 2; 
    }

    .logo-container img {
        max-width: 600px !important; 
        height: auto;
        display: block;
        margin: 0 auto;
    }

    .video-foreground video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
</style>

<div class="container-fluid px-0">
    <div class="video-background">
        <div class="video-overlay"></div>
        <div class="video-foreground">
            <video width="100%" height="100%" autoplay loop muted>
                <source src="{{ url_for('static', filename='photos/home_pictures/video2.mp4') }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
        <img src="{{ url_for('static', filename='photos/home_pictures/logo_with_border.png') }}" alt="Headliners Barber Shop" class="img-fluid" style="max-width: 600px;">
        <h1 class="text-center mt-3" style="color:'white'; letter-spacing: 1.3px;">Award Winning Barbershop</h1> 
        <a type="button" class="btn btn-outline-primary m-3" href="/barbers">See the team</a>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<form method="POST" class="mx-auto mt-5 flex-column align-items-center" style="width: 60vh">
    <h3 class="text-center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
    <a class="m-2" href="/sign-up">Need to sign up?</a>
</form>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<style>
    .profile-container {
        background-color: #1e1e1e;
        color: #cacaca;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(78, 0, 0, 0.2);
    }

    .profile-picture {
        width: 350px; 
        height: 350px;
        object-fit: cover; 
        border-radius: 10px;
        border: 4px solid #fff; 
    }

    .instagram-link {
        text-decoration: none;
        color: #bb3434;
    }

    .instagram-link:hover {
        text-decoration: underline;
    }
</style>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <div class="profile-container">
                <!-- Profile Picture -->
                <div class="text-center">
                    <img src="{{ url_for('static', filename='photos/profile_pictures/' + barber.barber_detail.picture_filename) }}" alt="{{ barber.name }}" class="img-fluid profile-picture">
                </div>
                <!-- Instagram Link -->
                <div class="text-center mt-3">
                    <a href="https://www.instagram.com/{{ barber.barber_detail.instagram_tag }}" target="_blank" class="instagram-link">
                        <i class="fab fa-instagram"></i> Follow on Instagram
                    </a>
                </div>
                <!-- Barber Details -->
                <div class="mt-4">
                    <h2>{{ barber.name }}</h2>
                    <p><strong>Phone:</strong> {{ barber.phone_number }}</p>
                    <p><strong>Email:</strong> <a href="mailto:{{ barber.email }}">{{ barber.email }}</a></p>
                </div>
                <!-- Booking Button -->
                <div class="text-center mt-4">
                    <a href="{{ url_for('book.book_appointment', barber_id=barber.barber_detail.barber_id) }}" class="btn btn-primary">Book Appointment</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/send_message.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5" style="width: 60vh">
    <h2 class="text-center">Send Message</h2>
    <form method="post" action="{{ url_for('messages.send_message') }}">
        <div class="mb-3">
            <label class="form-label">Recipient</label>
            {% if user.role == 'barber' %}
                <!-- Barber sending to clients: Use checkboxes -->
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="all_past_clients" id="all_past_clients">
                    <label class="form-check-label" for="all_past_clients">
                        Send to All Past Clients
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="all_clients" id="all_clients">
                    <label class="form-check-label" for="all_clients">
                        Send to All Clients
                    </label>
                </div>
                {% for client in recipients %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="receivers" value="{{ client.user_id }}" id="client{{ client.user_id }}"
                               {% if preselected_recipient and preselected_recipient.user_id == client.user_id %} checked {% endif %}>
                        <label class="form-check-label" for="client{{ client.user_id }}">
                            {{ client.name }}
                        </label>
                    </div>
                {% endfor %}
            {% else %}
                <!-- Client sending to a barber: Use dropdown -->
                <select class="form-select" id="receiver" name="receiver">
                    {% for barber in recipients %}
                        <option value="{{ barber.user_id }}" {% if preselected_recipient and preselected_recipient.user_id == barber.user_id %}selected{% endif %}>{{ barber.user.name }}</option>
                    {% endfor %}
                </select>
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Message</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

website/templates/services.html
<!-- page for barbers to view and manage all of their Services -->
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5">
    <h1 class="text-left">Barber Services</h1>
    <a href="{{ url_for('dashboard.add_service') }}" class="btn btn-primary mb-3">Add Service</a>
    <div class="row">
        {% for service in barber.services %}
        <div class="col-md-4 mb-4">
            <div class="card custom-card">
                <div class="card-body">
                    <h5 class="card-title">{{ service.name }}</h5>
                    <p class="card-text">{{ service.desc }}</p>
                    <p class="card-text">Price: ${{ service.price }}</p>
                    <p class="card-text">Duration: {{ service.duration }} minutes</p>
                    <a href="{{ url_for('dashboard.edit_service', service_id=service.barber_service_id) }}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{{ url_for('dashboard.delete_service', service_id=service.barber_service_id) }}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}

{% block content %}
<form method="POST" class="mx-auto mt-5 flex-column align-items-center" style="width: 60vh">
    <h3 class="text-center">Register</h3>
    <select name="role" id="role" class="form-control mt-4 mb-4" required>
        <option value="client">Client</option>
        <option value="barber">Barber</option>
    </select>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name">
    </div>
    <div class="form-group">
        <label for="phone_number">Phone Number</label>
        <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Enter phone number">
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
    </div>
    <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="m-2" href="/login">Already have an account?</a>

</form>
{% endblock %}